import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{vue,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0d1515',
        'surface-dim': '#0d1515',
        'surface-bright': '#323b3b',
        'surface-container-lowest': '#081010',
        'surface-container-low': '#151d1d',
        'surface-container': '#192121',
        'surface-container-high': '#232b2c',
        'surface-container-highest': '#2e3637',
        'on-surface': '#dce4e4',
        'on-surface-variant': '#b9caca',
        'inverse-surface': '#dce4e4',
        'inverse-on-surface': '#2a3232',
        outline: '#849495',
        'outline-variant': '#3a494a',
        'surface-tint': '#00dce5',
        primary: '#e9feff',
        'on-primary': '#003739',
        'primary-container': '#00f5ff',
        'on-primary-container': '#006c71',
        'inverse-primary': '#00696e',
        secondary: '#ffb77d',
        'on-secondary': '#4d2600',
        'secondary-container': '#fd8b00',
        'on-secondary-container': '#603100',
        tertiary: '#fff9f0',
        'on-tertiary': '#3a3000',
        'tertiary-container': '#ffdb40',
        'on-tertiary-container': '#736000',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#63f7ff',
        'primary-fixed-dim': '#00dce5',
        'on-primary-fixed': '#002021',
        'on-primary-fixed-variant': '#004f53',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'on-secondary-fixed': '#2f1500',
        'on-secondary-fixed-variant': '#6e3900',
        'tertiary-fixed': '#ffe16d',
        'tertiary-fixed-dim': '#e9c400',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#544600',
        background: '#0d1515',
        'on-background': '#dce4e4',
        'surface-variant': '#2e3637',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'code-lg': ['"JetBrains Mono"', 'monospace'],
        'code-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '700' }],
        'code-lg': ['16px', { lineHeight: '1.2', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '1.2', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        margin: '24px',
        'container-padding': '20px',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: '1', filter: 'drop-shadow(0 0 4px currentColor)' },
          '50%': { opacity: '0.5', filter: 'drop-shadow(0 0 8px currentColor)' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
} satisfies Config
